C-----------------------------------------------------------------------
C     Files.Inc
C 
C     Date:       7/29/96
C
C     Description:   Contains the path and filenames of the various
C                    files used
C
C-----------------------------------------------------------------------
      
      CHARACTER*50   listfile, rsfile, metfile, outfile, 
     &               nucdatfile, nuclfile
     
      COMMON /files/
     &               listfile, rsfile, metfile, outfile, 
     &               nucdatfile, nuclfile