C    .......FOR                      Version Date: 30-Oct-96               
C   Copyright 1996 by Battelle Memorial Institute.  All rights reserved.
C*****************************************************************************
C                                                                            *
C                           SUBROUTINE ......                                *
C                                                                            *
C  Subroutine ......                                                         *
C                                                                            *
C  Written by:       Dl Strenge                                              *
C                    Battelle Pacific Northwest Laboratories                 *
C                    P.O. Box 999                                            *
C                    Richland, WA 99352                                      *
C                                                                            *
C  Creation Date:    30-Oct-96                                               *
C  Last Modified:    30-Oct-96      DLS                                      *
C                                                                            *
C*****************************************************************************
C
C==== Modular Organization ===================================================
C
C     Module of: ......       
C     Called by: ...
C     Calls: NONE  
C     Common blocks referenced: NONE
C
C==== Significant Parameter Designation and Description ======================
C
C     Parameter Set/
C     Name      Used   Type    Location  Parameter Description
C     --------- -----  ------  --------- -------------------------------------
C     SETDATA    S      CHR    GID file  Storage array for GID data set 
C
C==== Modification History ===================================================
C     Date         Who  Modification Description
C     --------     ---  ------------------------------------------------------
C   30-Oct-96      DLS  Initial programming started
C==== SUBROUTINE CALL ========================================================
C
      SUBROUTINE ......()
C      
C---- Variable Type Declarations ---------------------------------------------
C
      LOGICAL 
      INTEGER 
      CHARACTER*
      CHARACTER*
C
C---- Data Statements --------------------------------------------------------
C
C
C---- Start of Analysis
C  
      




      RETURN
C----- END OF MODULE ...... -------------------------------------------------
      END

