"src2",28
"================================================================================",
"  Source Term Release Module Version: Framework PoP  January 1997  ",
"  Run:","D:\FUI\~glyph",
"  Site:","src2",
"  Run Performed:","7/31/1999","10:14:51",
"  Output Filename:","D:\FUI\~glyph.sls",
"================================================================================",


"Analysis is for BASELINE case.",

"The starting value for the wind erosion rate is:",0,"(cm/y)",

"The starting value for the surface water erosion rate is:",0,"(cm/y)",

"The starting value for the infiltration rate is:",20,"(cm/y)",

"Initializing contaminant data",
"Contaminants evaluated for this run",
"NUM","CAS_ID","PARENT_ID","NAME","NUM PROGENY",
0,"71432","71432","Benzene",0,
1,"SR90","SR90","STRONTIUM-90",1,
2,"Y90","SR90","YTTRIUM-90",0,
3,"TC99","TC99","TECHNECIUM-99",0,

"All the mass for contaminant:",0,"lost at time:",121,
"All the mass for contaminant:",1,"lost at time:",190,
"All the mass for contaminant:",2,"lost at time:",191,
"src32",29
"================================================================================",
"  Source Term Release Module Version: Framework PoP  January 1997  ",
"  Run:","D:\FUI\~glyph",
"  Site:","src32",
"  Run Performed:","7/31/1999","10:23:33",
"  Output Filename:","D:\FUI\~glyph.sls",
"================================================================================",


"Analysis is for BASELINE case.",

"The starting value for the wind erosion rate is:",0,"(cm/y)",

"The starting value for the surface water erosion rate is:",10,"(cm/y)",

"The starting value for the infiltration rate is:",0,"(cm/y)",

"Initializing contaminant data",
"Contaminants evaluated for this run",
"NUM","CAS_ID","PARENT_ID","NAME","NUM PROGENY",
0,"71432","71432","Benzene",0,
1,"SR90","SR90","STRONTIUM-90",1,
2,"Y90","SR90","YTTRIUM-90",0,
3,"TC99","TC99","TECHNECIUM-99",0,

"All the mass for contaminant:",1,"lost at time:",93,
"All the mass for contaminant:",2,"lost at time:",94,
"All the mass for contaminant:",3,"lost at time:",100,
"All the mass for contaminant:",0,"lost at time:",101,
"src35",29
"================================================================================",
"  Source Term Release Module Version: Framework PoP  January 1997  ",
"  Run:","D:\FUI\~glyph",
"  Site:","src35",
"  Run Performed:","7/31/1999","10:27:18",
"  Output Filename:","D:\FUI\~glyph.sls",
"================================================================================",


"Analysis is for BASELINE case.",

"The starting value for the wind erosion rate is:",10,"(cm/y)",

"The starting value for the surface water erosion rate is:",0,"(cm/y)",

"The starting value for the infiltration rate is:",0,"(cm/y)",

"Initializing contaminant data",
"Contaminants evaluated for this run",
"NUM","CAS_ID","PARENT_ID","NAME","NUM PROGENY",
0,"71432","71432","Benzene",0,
1,"SR90","SR90","STRONTIUM-90",1,
2,"Y90","SR90","YTTRIUM-90",0,
3,"TC99","TC99","TECHNECIUM-99",0,

"All the mass for contaminant:",1,"lost at time:",93,
"All the mass for contaminant:",2,"lost at time:",94,
"All the mass for contaminant:",3,"lost at time:",100,
"All the mass for contaminant:",0,"lost at time:",101,
"src38",27
"================================================================================",
"  Source Term Release Module Version: Framework PoP  January 1997  ",
"  Run:","D:\FUI\~glyph",
"  Site:","src38",
"  Run Performed:","7/31/1999","10:28:38",
"  Output Filename:","D:\FUI\~glyph.sls",
"================================================================================",


"Analysis is for BASELINE case.",

"The starting value for the wind erosion rate is:",0,"(cm/y)",

"The starting value for the surface water erosion rate is:",0,"(cm/y)",

"The starting value for the infiltration rate is:",0,"(cm/y)",

"Initializing contaminant data",
"Contaminants evaluated for this run",
"NUM","CAS_ID","PARENT_ID","NAME","NUM PROGENY",
0,"71432","71432","Benzene",0,
1,"SR90","SR90","STRONTIUM-90",1,
2,"Y90","SR90","YTTRIUM-90",0,
3,"TC99","TC99","TECHNECIUM-99",0,

"All the mass for contaminant:",1,"lost at time:",194,
"All the mass for contaminant:",2,"lost at time:",195,
"src42",0000000029
"================================================================================",
"  Source Term Release Module Version: Framework PoP  January 1997  ",
"  Run:","D:\FUI\~glyph",
"  Site:","src42",
"  Run Performed:","7/31/1999","11:1:13",
"  Output Filename:","D:\FUI\~glyph.sls",
"================================================================================",


"Analysis is for BASELINE case.",

"The starting value for the wind erosion rate is:",10,"(cm/y)",

"The starting value for the surface water erosion rate is:",10,"(cm/y)",

"The starting value for the infiltration rate is:",20,"(cm/y)",

"Initializing contaminant data",
"Contaminants evaluated for this run",
"NUM","CAS_ID","PARENT_ID","NAME","NUM PROGENY",
0,"71432","71432","Benzene",0,
1,"SR90","SR90","STRONTIUM-90",1,
2,"Y90","SR90","YTTRIUM-90",0,
3,"TC99","TC99","TECHNECIUM-99",0,

"All the mass for contaminant:",0,"lost at time:",47,
"All the mass for contaminant:",3,"lost at time:",50,
"All the mass for contaminant:",1,"lost at time:",50,
"All the mass for contaminant:",2,"lost at time:",51,
