ECHO OFF
ECHO Error MEPAS Vadose Zone Module > %2.ERR
ECHO ON
COPY %1.wff MEPASBAK.WFF
PreVadoseG %1 %2 %3 %4 %5
IF ERRORLEVEL 1 GOTO ERROR
RADCON.EXE
IF ERRORLEVEL 1 GOTO ERROR
IF EXIST MEPAS_VZ.ERR GOTO ERROR
GOTO OK
:ERROR
IF EXIST MEPAS_VZ.ERR COPY MEPAS_VZ.ERR %2.ERR
IF EXIST MEPAS_VZ.WLS COPY MEPAS_VZ.WLS %2.WLS
IF EXIST MEPAS_VZ.WRN COPY MEPAS_VZ.WRN %2.WRN
DEL MEPAS_VZ.ERR
GOTO END
:OK
PostVadoseG %1.gid %2.gff %3 %4 %5 MEPAS_VZ.WFF > MEPAS_VZ.ERR
IF ERRORLEVEL 1 GOTO ERROR
IF EXIST MEPAS_VZ.WLS COPY MEPAS_VZ.WLS %2.WLS
IF EXIST MEPAS_VZ.WRN COPY MEPAS_VZ.WRN %2.WRN
DEL %2.ERR
:END
DEL %1.wff
COPY MEPASBAK.WFF %1.wff
DEL MEPASBAK.WFF
DEL FACIL.ID
DEL MEPAS_VZ.DBG
DEL MEPAS_VZ.WFF
DEL MEPAS_VZ.WLS
DEL MEPAS_VZ.WRN
DEL MEPAS_VZ.POL
DEL MEPAS_VZ.WIN