C-----------------------------------------------------------------------
C
C     Parm.INC
C
C     Date:    8/16/96
C
C     Description:   Contains the parameter for FRMCONC
C
C-----------------------------------------------------------------------
      INTEGER  MaxDist, NumDir, NumDist, MaxType
      
      PARAMETER( MaxDist = 12 )
      PARAMETER( NumDist = 20 )
      PARAMETER( NumDir = 16 )
      PARAMETER( MaxType = 7 )
      