/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_epa_hwir_util_hwirio */

#ifndef _Included_gov_epa_hwir_util_hwirio
#define _Included_gov_epa_hwir_util_hwirio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    IOOk
 * Signature: ()V
 */
JNIEXPORT jboolean JNICALL Java_gov_epa_hwir_util_hwirio_IOOk
  (JNIEnv *, jobject);
/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    setArgs
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_setArgs
  (JNIEnv *, jobject, jstring);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    setArgsSystem
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_setArgsSystem
  (JNIEnv *, jobject, jstring);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    getStatus
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_gov_epa_hwir_util_hwirio_getStatus
  (JNIEnv *, jobject);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    resetArgs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_resetArgs
  (JNIEnv *, jobject);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    addGroup
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_addGroup
  (JNIEnv *, jobject, jstring);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    addRWGroup
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_addRWGroup
  (JNIEnv *, jobject, jstring);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    removeGroup
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_removeGroup
  (JNIEnv *, jobject, jstring);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    numArgs
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gov_epa_hwir_util_hwirio_numArgs
  (JNIEnv *, jobject);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    getArgInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_gov_epa_hwir_util_hwirio_getArgInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    getArgString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_epa_hwir_util_hwirio_getArgString
  (JNIEnv *, jobject, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    openGroups
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_openGroups
  (JNIEnv *, jobject);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    closeGroups
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_closeGroups
  (JNIEnv *, jobject);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    error
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_error
  (JNIEnv *, jobject, jstring);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    warning
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_warning
  (JNIEnv *, jobject, jstring);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    readInt
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_gov_epa_hwir_util_hwirio_readInt__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    readInt
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_gov_epa_hwir_util_hwirio_readInt__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    readInt
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_gov_epa_hwir_util_hwirio_readInt__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2II
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    readInt
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_gov_epa_hwir_util_hwirio_readInt__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2III
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    readInt
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIII)I
 */
JNIEXPORT jint JNICALL Java_gov_epa_hwir_util_hwirio_readInt__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIII
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    readInt
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIII)I
 */
JNIEXPORT jint JNICALL Java_gov_epa_hwir_util_hwirio_readInt__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIIII
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    readInt
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIII)I
 */
JNIEXPORT jint JNICALL Java_gov_epa_hwir_util_hwirio_readInt__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIIIII
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint, jint, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    writeInt
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_writeInt__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    writeInt
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_writeInt__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2II
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    writeInt
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;III)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_writeInt__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2III
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    writeInt
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIII)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_writeInt__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIII
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    writeInt
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIII)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_writeInt__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIIII
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    writeInt
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIII)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_writeInt__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIIIII
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint, jint, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    writeInt
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIIII)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_writeInt__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIIIIII
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    readReal
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_gov_epa_hwir_util_hwirio_readReal__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    readReal
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)D
 */
JNIEXPORT jdouble JNICALL Java_gov_epa_hwir_util_hwirio_readReal__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    readReal
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;II)D
 */
JNIEXPORT jdouble JNICALL Java_gov_epa_hwir_util_hwirio_readReal__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2II
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    readReal
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;III)D
 */
JNIEXPORT jdouble JNICALL Java_gov_epa_hwir_util_hwirio_readReal__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2III
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    readReal
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIII)D
 */
JNIEXPORT jdouble JNICALL Java_gov_epa_hwir_util_hwirio_readReal__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIII
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    readReal
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIII)D
 */
JNIEXPORT jdouble JNICALL Java_gov_epa_hwir_util_hwirio_readReal__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIIII
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    readReal
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIII)D
 */
JNIEXPORT jdouble JNICALL Java_gov_epa_hwir_util_hwirio_readReal__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIIIII
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint, jint, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    writeReal
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_writeReal__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2D
  (JNIEnv *, jobject, jstring, jstring, jstring, jdouble);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    writeReal
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ID)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_writeReal__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2ID
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jdouble);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    writeReal
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IID)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_writeReal__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IID
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jdouble);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    writeReal
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIID)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_writeReal__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIID
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jdouble);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    writeReal
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIID)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_writeReal__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIIID
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint, jdouble);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    writeReal
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIID)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_writeReal__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIIIID
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint, jint, jdouble);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    writeReal
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIIID)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_writeReal__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIIIIID
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint, jint, jint, jdouble);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    readLog
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_epa_hwir_util_hwirio_readLog__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    readLog
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_epa_hwir_util_hwirio_readLog__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    readLog
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_epa_hwir_util_hwirio_readLog__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2II
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    readLog
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;III)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_epa_hwir_util_hwirio_readLog__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2III
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    readLog
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_epa_hwir_util_hwirio_readLog__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIII
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    readLog
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_epa_hwir_util_hwirio_readLog__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIIII
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    readLog
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_gov_epa_hwir_util_hwirio_readLog__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIIIII
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint, jint, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    writeLog
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_writeLog__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Z
  (JNIEnv *, jobject, jstring, jstring, jstring, jboolean);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    writeLog
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IZ)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_writeLog__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IZ
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jboolean);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    writeLog
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIZ)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_writeLog__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIZ
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jboolean);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    writeLog
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIZ)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_writeLog__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIIZ
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jboolean);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    writeLog
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIZ)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_writeLog__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIIIZ
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint, jboolean);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    writeLog
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIIZ)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_writeLog__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIIIIZ
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint, jint, jboolean);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    writeLog
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIIIZ)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_writeLog__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIIIIIZ
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint, jint, jint, jboolean);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    readString
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_epa_hwir_util_hwirio_readString__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    readString
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_epa_hwir_util_hwirio_readString__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    readString
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_epa_hwir_util_hwirio_readString__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2II
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    readString
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_epa_hwir_util_hwirio_readString__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2III
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    readString
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_epa_hwir_util_hwirio_readString__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIII
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    readString
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_epa_hwir_util_hwirio_readString__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIIII
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    readString
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gov_epa_hwir_util_hwirio_readString__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIIIII
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint, jint, jint);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    writeString
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_writeString__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    writeString
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_writeString__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2ILjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jstring);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    writeString
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_writeString__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IILjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jstring);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    writeString
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_writeString__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIILjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jstring);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    writeString
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_writeString__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIIILjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint, jstring);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    writeString
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_writeString__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIIIILjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint, jint, jstring);

/*
 * Class:     gov_epa_hwir_util_hwirio
 * Method:    writeString
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_hwirio_writeString__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2IIIIIILjava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
