/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_epa_hwir_util_StatDll */

#ifndef _Included_gov_epa_hwir_util_StatDll
#define _Included_gov_epa_hwir_util_StatDll
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gov_epa_hwir_util_StatDll
 * Method:    StatClear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_StatDll_StatClear
  (JNIEnv *, jobject);

/*
 * Class:     gov_epa_hwir_util_StatDll
 * Method:    StatCor
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_StatDll_StatCor
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     gov_epa_hwir_util_StatDll
 * Method:    StatDebugOn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_StatDll_StatDebugOn
  (JNIEnv *, jobject);

/*
 * Class:     gov_epa_hwir_util_StatDll
 * Method:    StatExponential
 * Signature: (DDD)I
 */
JNIEXPORT jint JNICALL Java_gov_epa_hwir_util_StatDll_StatExponential
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     gov_epa_hwir_util_StatDll
 * Method:    StatGamma
 * Signature: (DDDD)I
 */
JNIEXPORT jint JNICALL Java_gov_epa_hwir_util_StatDll_StatGamma
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     gov_epa_hwir_util_StatDll
 * Method:    StatIntUniform
 * Signature: (DD)I
 */
JNIEXPORT jint JNICALL Java_gov_epa_hwir_util_StatDll_StatIntUniform
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     gov_epa_hwir_util_StatDll
 * Method:    StatLogNormal
 * Signature: (DDDD)I
 */
JNIEXPORT jint JNICALL Java_gov_epa_hwir_util_StatDll_StatLogNormal
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     gov_epa_hwir_util_StatDll
 * Method:    StatNormal
 * Signature: (DDDD)I
 */
JNIEXPORT jint JNICALL Java_gov_epa_hwir_util_StatDll_StatNormal
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     gov_epa_hwir_util_StatDll
 * Method:    StatNumCor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_StatDll_StatNumCor
  (JNIEnv *, jobject, jint);

/*
 * Class:     gov_epa_hwir_util_StatDll
 * Method:    StatNumDist
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_StatDll_StatNumDist
  (JNIEnv *, jobject, jint);

/*
 * Class:     gov_epa_hwir_util_StatDll
 * Method:    StatSB
 * Signature: (DDDD)I
 */
JNIEXPORT jint JNICALL Java_gov_epa_hwir_util_StatDll_StatSB
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     gov_epa_hwir_util_StatDll
 * Method:    StatSU
 * Signature: (DDDD)I
 */
JNIEXPORT jint JNICALL Java_gov_epa_hwir_util_StatDll_StatSU
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     gov_epa_hwir_util_StatDll
 * Method:    StatSeed
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_gov_epa_hwir_util_StatDll_StatSeed
  (JNIEnv *, jobject, jint);

/*
 * Class:     gov_epa_hwir_util_StatDll
 * Method:    StatTriangular
 * Signature: (DDD)I
 */
JNIEXPORT jint JNICALL Java_gov_epa_hwir_util_StatDll_StatTriangular
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     gov_epa_hwir_util_StatDll
 * Method:    StatTrnLogNormal
 * Signature: (DDDD)I
 */
JNIEXPORT jint JNICALL Java_gov_epa_hwir_util_StatDll_StatTrnLogNormal
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     gov_epa_hwir_util_StatDll
 * Method:    StatUniform
 * Signature: (DD)I
 */
JNIEXPORT jint JNICALL Java_gov_epa_hwir_util_StatDll_StatUniform
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     gov_epa_hwir_util_StatDll
 * Method:    StatWeibull
 * Signature: (DDDD)I
 */
JNIEXPORT jint JNICALL Java_gov_epa_hwir_util_StatDll_StatWeibull
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);


JNIEXPORT jint JNICALL Java_gov_epa_hwir_util_StatDll_StatEmpirical
(JNIEnv *, jobject , jdouble , jdouble , jint , jdoubleArray , jdoubleArray );


JNIEXPORT void JNICALL Java_gov_epa_hwir_util_StatDll_StatSample
(JNIEnv *, jobject , jint , jdoubleArray );

#ifdef __cplusplus

}
#endif
#endif
