@REM Compile AIRCAL.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk AIRCAL.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile AIRSAVE.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk AIRSAVE.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile AIRSET.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk AIRSET.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile ANMCAL.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk ANMCAL.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile AQUCAL.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk AQUCAL.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile ATODAT.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk ATODAT.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile ATOIN.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk ATOIN.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile AVGCON.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk AVGCON.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile BLKDAT.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk BLKDAT.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile BLOCKD.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk BLOCKD.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile CANDH.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk CANDH.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile CHAIN.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk CHAIN.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile CRPCAL.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk CRPCAL.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile DKHARV.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk DKHARV.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile DRKCAL.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk DRKCAL.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile EDRANM.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk EDRANM.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile EDRCRP.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk EDRCRP.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile EDRRES.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk EDRRES.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile ENV.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk ENV.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile ENVLIB.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk ENVLIB.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile EPFDAT.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk EPFDAT.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile EPFDSET.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk EPFDSET.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile EPFGRID.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk EPFGRID.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile EPFHEAD.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk EPFHEAD.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile EXPOS.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk EXPOS.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile EXPOSR.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk EXPOSR.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile EXTCAL.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk EXTCAL.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile FILERR.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk FILERR.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile GETINT.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk GETINT.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile GETLEACH.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk GETLEACH.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile GETLOG.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk GETLOG.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile GETNAM.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk GETNAM.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile GETREAL.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk GETREAL.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile GETSET.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk GETSET.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile GETSTR.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk GETSTR.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile GETXY.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk GETXY.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile HEADIN.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk HEADIN.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile HEADNG.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk HEADNG.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile INHCAL.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk INHCAL.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile INITNV.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk INITNV.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile LENWORD.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk LENWORD.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile MAKDA2.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk MAKDA2.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile MARKIN.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk MARKIN.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile MOVESET.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk MOVESET.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile MOVETO.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk MOVETO.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile OPNFIL.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk OPNFIL.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile REDCAS.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk REDCAS.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile RMDGET.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk RMDGET.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile SEQ.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk SEQ.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile SEQI.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk SEQI.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile SETAIR.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk SETAIR.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile SETANION.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk SETANION.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile SETCON.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk SETCON.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile SETELAW.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk SETELAW.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile TRNSPT.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk TRNSPT.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile UPPERC.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk UPPERC.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile VINTERP.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk VINTERP.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile WCFDAT.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk WCFDAT.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile WCFIN.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk WCFIN.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Compile XYPOINT.FOR (no object file)
@lf90 -c -WIN -trap dio -o2 -chk -stchk XYPOINT.FOR
@IF ERRORLEVEL 1 GOTO QUIT

@REM Relink expos.exe (Newly compiled object files)
@amrsp--f
@lf90 @AUTOMAKE.RSP -o2 -exe expos.exe -mod .\ -bind
:QUIT
