"src2",27
"================================================================================",
"  Source Term Release Module Version: Framework PoP  January 1997  ",
"  Run:","D:\FUI\~glyph",
"  Site:","src2",
"  Run Performed:","8/1/1999","19:56:22",
"  Output Filename:","D:\FUI\~glyph.sls",
"================================================================================",


"Analysis is for BASELINE case.",

"The starting value for the wind erosion rate is:",0,"(cm/y)",

"The starting value for the surface water erosion rate is:",0,"(cm/y)",

"The starting value for the infiltration rate is:",20,"(cm/y)",

"Initializing contaminant data",
"Contaminants evaluated for this run",
"NUM","CAS_ID","PARENT_ID","NAME","NUM PROGENY",
0,"71432","71432","Benzene",0,
1,"SR90","SR90","STRONTIUM-90",1,
2,"Y90","SR90","YTTRIUM-90",0,
3,"TC99","TC99","TECHNECIUM-99",0,

"All the mass for contaminant:",1,"lost at time:",233,
"All the mass for contaminant:",2,"lost at time:",234,
"src32",24
"================================================================================",
"  Source Term Release Module Version: Framework PoP  January 1997  ",
"  Run:","D:\FUI\~glyph",
"  Site:","src32",
"  Run Performed:","8/1/1999","20:23:30",
"  Output Filename:","D:\FUI\~glyph.sls",
"================================================================================",


"Analysis is for BASELINE case.",

"The starting value for the wind erosion rate is:",0,"(cm/y)",

"The starting value for the surface water erosion rate is:",0,"(cm/y)",

"The starting value for the infiltration rate is:",0,"(cm/y)",

"Initializing contaminant data",
"Contaminants evaluated for this run",
"NUM","CAS_ID","PARENT_ID","NAME","NUM PROGENY",
0,"71432","71432","Benzene",0,
1,"SR90","SR90","STRONTIUM-90",1,
2,"Y90","SR90","YTTRIUM-90",0,
3,"TC99","TC99","TECHNECIUM-99",0,
"src35",26
"================================================================================",
"  Source Term Release Module Version: Framework PoP  January 1997  ",
"  Run:","D:\FUI\~glyph",
"  Site:","src35",
"  Run Performed:","8/1/1999","20:31:6",
"  Output Filename:","D:\FUI\~glyph.sls",
"================================================================================",


"Analysis is for BASELINE case.",

"The starting value for the wind erosion rate is:",0,"(cm/y)",

"The starting value for the surface water erosion rate is:",0,"(cm/y)",

"The starting value for the infiltration rate is:",0,"(cm/y)",

"Initializing contaminant data",
"Contaminants evaluated for this run",
"NUM","CAS_ID","PARENT_ID","NAME","NUM PROGENY",
0,"71432","71432","Benzene",0,
1,"SR90","SR90","STRONTIUM-90",1,
2,"Y90","SR90","YTTRIUM-90",0,
3,"TC99","TC99","TECHNECIUM-99",0,

"All the mass for contaminant:",0,"lost at time:",219,
"src38",24
"================================================================================",
"  Source Term Release Module Version: Framework PoP  January 1997  ",
"  Run:","D:\FUI\~glyph",
"  Site:","src38",
"  Run Performed:","8/1/1999","20:38:34",
"  Output Filename:","D:\FUI\~glyph.sls",
"================================================================================",


"Analysis is for BASELINE case.",

"The starting value for the wind erosion rate is:",0,"(cm/y)",

"The starting value for the surface water erosion rate is:",0,"(cm/y)",

"The starting value for the infiltration rate is:",0,"(cm/y)",

"Initializing contaminant data",
"Contaminants evaluated for this run",
"NUM","CAS_ID","PARENT_ID","NAME","NUM PROGENY",
0,"71432","71432","Benzene",0,
1,"SR90","SR90","STRONTIUM-90",1,
2,"Y90","SR90","YTTRIUM-90",0,
3,"TC99","TC99","TECHNECIUM-99",0,
"src42",0000000028
"================================================================================",
"  Source Term Release Module Version: Framework PoP  January 1997  ",
"  Run:","D:\FUI\~glyph",
"  Site:","src42",
"  Run Performed:","8/1/1999","20:46:22",
"  Output Filename:","D:\FUI\~glyph.sls",
"================================================================================",


"Analysis is for BASELINE case.",

"The starting value for the wind erosion rate is:",0,"(cm/y)",

"The starting value for the surface water erosion rate is:",0,"(cm/y)",

"The starting value for the infiltration rate is:",20,"(cm/y)",

"Initializing contaminant data",
"Contaminants evaluated for this run",
"NUM","CAS_ID","PARENT_ID","NAME","NUM PROGENY",
0,"71432","71432","Benzene",0,
1,"SR90","SR90","STRONTIUM-90",1,
2,"Y90","SR90","YTTRIUM-90",0,
3,"TC99","TC99","TECHNECIUM-99",0,

"All the mass for contaminant:",0,"lost at time:",133,
"All the mass for contaminant:",1,"lost at time:",233,
"All the mass for contaminant:",2,"lost at time:",234,
