git add "ATO GNUPlot"
git add "Acute"
git add "Air Gen"
git add "Air UI"
git add "Aquifer UI"
git add "AquiferG UI"
git add "Autotests"
git add "Batch Files"
git add "BatchUtil"
git add "Biota Viewer"
git add "Biota"
git add "CHIQ"
git add "Chronic"
git add "Common Files"
git add "Contaminant Selection"
# git add "DOT"
# git add "DSP"
git add "Description Editor"
git add "Description Files"
git add "Documents"
git add "Dummy Module"
git add "Eco Benchmarks"
git add "Exposure UI"
git add "Exposure"
git add FRAMES.bpg FRAMES.vbg
git add "Frames DLL"
git add "Frames IO DLL"
git add "Frames UI"
git add "FramesStatus"
# git add "GENII UIs"
# git add "GENII.VBG"
git add "GIS UI"
git add GIS.bpg         GIS.vbg
git add "GTvad"
git add "GeoPrePop"
git add "Graphical Viewer"
git add "Health Impacts UI"
git add "Health Impacts"
git add "Icons"
git add "ImportDES"
git add "ImportGID"
git add "InpCheck"
git add "Intake"
git add "JFDGenerator"
git add "KP_API_DEV"
git add "Kd&HalfLife Update"
git add "Known ATO"
git add "Known BBF"
git add "Known EPF"
git add "Known RIF"
git add "Known SCF_WFF_AFF_WCF"
git add "KnownG GFF"
git add "Latin"
git add MEPAS.bpg        MEPAS.vbg        Master.dsw        Master.ncb        Master.opt
# git add "Messenger"
git add "MetProcessors"
git add "Modules"
# git add "NEAR"
# git add "NESHAPS UIs"
# git add "NESHAPS Viewer"
git add "Online Help"
# git add "PAR"
# git add "PickSrc"
git add "Plume"
git add "Plus Operator"
git add "Population Risk Viewer"
git add "Post VadoseG"
git add "Pre AquiferG"
git add "Pre Exposure"
# git add Pre Radcon.zip
git add "Pre Radcon"
git add "Pre VadoseG"
git add "PrePre Aquifer"
git add "Puff"
git add "RAGS Tables"
# git add "RAvad"
git add "Radcon"
git add "Rapscd"
git add "Receptor UI"
git add "Receptor"
git add "River UI"
git add "Run1xMod"
git add "SCF Import"
git add "SUMod"
git add "SW Viewer"
git add "SWATER"
git add "Secondary Source"
git add "Sensitivity Module"
git add "Sensitivity UI"
# git add "Sensitivity1.6"
git add "SensitivityViewer"
git add "Software required to build.doc"
git add "Source Term UI"
git add "Source Term"
git add "Star"
git add "Sync UI"
git add "System"
git add "Template"
git add "TestLauncher"
git add "Text Viewer"
git add "Trim WFF,AFF"
git add VBInstaller2.cache        VBInstaller2.sln        VBInstaller2.suo        VBInstaller2.wip
git add "Vadose UI"
git add "VadoseG UI"
git add "Weap UI"
git add "Weap"
git add "WrapSpec"
git add "Wrapper"
git add all.xls
git add dddDescription Files
git add frames2xml
# git add "genhei2"
git add loglink.txt        readme.txt        renlink.bat

